name:                par-tree
version:             0.0.1.0
github:              "sitiritis/par-tree"
license:             BSD3
author:              "Tymur Lysenko"
maintainer:          "example@example.com"
copyright:           "2021 Tymur Lysenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category: Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/sitiritis/par-tree>

dependencies:
- base >= 4.7 && < 5
- prettyprinter == 1.7.1
- prettyprinter-ansi-terminal == 1.1.3
- text == 1.2.4.1

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings

executables:
  par-tree-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - par-tree
    when:
    - condition: false
      other-modules: Paths_par_tree

tests:
  par-tree-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - par-tree
