name: par-tree
version: 0.0.1.0
github: "sitiritis/par-tree"
license: BSD3
author: "Tymur Lysenko"
maintainer: "Tymur Lysenko"
copyright: "2021 Tymur Lysenko"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis: Short description of your package
category: Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/sitiritis/par-tree>

flags:
  gpu:
    description: When flag is set llvm-ptx accelerate backend will be used, which results in running all accelerate computations on a GPU. Otherwise, CPU backend is used.
    manual: true
    default: false

when:
  - condition: "flag(gpu)"
    then:
      cpp-options:
        - -DACCELERATE_LLVM_PTX_BACKEND
      dependencies:
        - accelerate-llvm-ptx == 1.3.0.0
    else:
      cpp-options:
        - -DACCELERATE_LLVM_NATIVE_BACKEND
      dependencies:
        - accelerate-llvm-native == 1.3.0.0

dependencies:
  - base >= 4.7 && < 5
  - text == 1.2.4.1
  - relude == 1.0.0.1
  - prettyprinter == 1.7.1
  - prettyprinter-ansi-terminal == 1.1.3
  - accelerate == 1.3.0.0

default-extensions:
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - NoImplicitPrelude
  - OverloadedStrings

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs: src

executables:
  par-tree-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - par-tree
    when:
      - condition: false
        other-modules: Paths_par_tree

tests:
  par-tree-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - StandaloneDeriving
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - par-tree
      - QuickCheck == 2.14.2
      - quickcheck-instances == 0.3.25.2
      - generic-random == 1.4.0.0
      - hspec == 2.7.10
